#!/usr/bin/env node
/*
 *********************************************************************************
 *                     Copyright (C) 2018 wystan
 *
 *       filename: server.js
 *    description:
 *        created: 2018-05-22 23:00:40
 *         author: wystan
 *
 *********************************************************************************
 */

const server_port = 8088;
const express = require('express');
let app = express();
app.use(express.static('static'));

app.listen(server_port);
console.log("http://localhost:" + server_port);
/************************************* END **************************************/
